#!/usr/bin/env bash

function _aws_vault_profile {
  local shome="${_aws_vault_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  export AWS_VAULT_KEYCHAIN_NAME='login'
}

_aws_vault_profile
