#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_awsvault="$(aws-vault --version 2>/dev/null | perl -pe 's{^v}{}' || true)"
  jq -n \
    --arg awsvault "$ver_awsvault" \
    '{awsvault: $awsvault}'
}

version "$@"
