#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_aws_vault="0.0.1"
  jq -n --arg aws_vault "$ver_aws_vault" '{aws_vault: $aws_vault}'
}

version "$@"
